CHANGELOG.md
README.md
doc/pull_request_template.md

Others:
Added PR template
Added CHANGELOG

Extended README on how to install deps

---

.travis.yml

Title says all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/5)

Added initial Travis config file

---

.travis.yml
CMakeLists.txt
README.md

Fixes issue #4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/6)

Disable hardening and coverage build flags by default

---

CMakeLists.txt

- There are several compilation issues for gcc version < 5.0
- Other compilers such as clang and icc are not supported.
Signed-off-by: mkhodamh <mehrnaz.khodam.hazrati@intel.com>
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/12)

Updated CMakeList to comly with correct compiler version

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/15)

Fixed Travis deployment job

---

CHANGELOG.md
CMakeLists.txt
doc/includes/HLD-Security.adoc
src/world/RssObjectPositionExtractor.cpp

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/16)

Added support for gcc 4.8

---

.travis.yml

Just extended Travis to also build using 14.04 and gcc 4.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/18)

Added tests for Ubuntu 14.04 to Travis

---

doc/includes/HLD-Security.adoc
src/core/RssCheck.cpp
src/core/RssResponseTransformation.cpp
src/core/RssSituationExtraction.cpp
src/physics/Math.cpp
src/situation/RSSFormulas.cpp
src/situation/RssIntersectionChecker.cpp
src/world/RssObjectPositionExtractor.cpp
src/world/RssSituationCoordinateSystemConversion.cpp
tests/CMakeLists.txt
tests/core/RssCheckIntersectionTests.cpp
tests/core/RssCheckLateralTests.cpp
tests/core/RssCheckNotRelevantTests.cpp
tests/core/RssCheckOppositeDirectionTests.cpp
tests/core/RssCheckSameDirectionTests.cpp
tests/core/RssCheckTestBaseT.hpp
tests/core/RssCheckTests.cpp
tests/core/RssResponseResolvingTests.cpp
tests/core/RssResponseTransformationTests.cpp
tests/core/RssSituationExtractionInputRangeTests.cpp
tests/core/RssSituationExtractionSameDirectionTests.cpp
tests/physics/MathUnitTestsInputRangeChecks.cpp
tests/situation/RSSFormulaTestsInputRangeChecks.cpp
tests/situation/RssSituationCheckingInputRangeTests.cpp
tests/situation/RssSituationCheckingTestsIntersectionInputRangeTests.cpp
tests/situation/RssSituationCheckingTestsIntersectionNoPriority.cpp
tests/test_support/wrap_new.cpp

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/17)

Further tests

---

CMakeLists.txt
README.md
doc/includes/HLD-Security.adoc

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/19)

Better support for undefined behavior

---

.github/.travis/code_coverage.sh
.github/.travis/compile.sh
.github/.travis/deploy.sh
.travis.yml

Checklist:
Title says all. Additional debug build added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/23)

Moved Travis code into separate scripts

---

tests/core/RssCheckIntersectionTests.cpp
tests/core/RssCheckLateralTests.cpp
tests/core/RssCheckOppositeDirectionTests.cpp
tests/core/RssCheckSameDirectionTests.cpp
tests/core/RssCheckTestBaseT.hpp
tests/core/RssCheckTimeIndexTests.cpp

i.e. added RssCheckSameDirectionEgoInTheMiddleTestBase
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/25)

Extended tests

---

CHANGELOG.md
CMakeLists.txt
tests/CMakeLists.txt

Checklist:
* **Platform(s):** Ubuntu 16.04
* **Library version:** 1.1.0
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/26)

Added support for Clang 5 and Clang 6

---

.travis.yml

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/28)

Enable debug build for coverage

---

tests/CMakeLists.txt
tests/core/RssCheckNotRelevantTests.cpp
tests/core/RssCheckTestBaseT.hpp

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/30)

Add rss check not relevant tests

---

CHANGELOG.md
include/generated/ad_rss/situation/SituationVectorValidInputRange.hpp
include/generated/ad_rss/world/RoadAreaValidInputRange.hpp
include/generated/ad_rss/world/RoadSegmentValidInputRange.hpp
src/core/RssSituationExtraction.cpp
tests/CMakeLists.txt
tests/core/RssCheckLateralTests.cpp
tests/core/RssCheckNotRelevantTests.cpp
tests/core/RssCheckObjectTests.cpp
tests/core/RssCheckSceneTests.cpp
tests/core/RssCheckTestBaseT.hpp
tests/core/RssResponseTransformationTests.cpp
tests/generated/situation/SituationVectorValidInputRangeTests.cpp
tests/generated/world/RoadAreaValidInputRangeTests.cpp
tests/generated/world/RoadSegmentValidInputRangeTests.cpp
tests/generated/world/SceneValidInputRangeTests.cpp
tests/situation/RssSituationCheckingInputRangeTests.cpp

- WorldModel Object type/value
Signed-off-by: mkhodamh <mehrnaz.khodam.hazrati@intel.com>
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/24)

Added tests for Input data validity

---

CHANGELOG.md
doc/Main.adoc
doc/includes/Appendix.adoc

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/31)

Release 1.2.0

---

CHANGELOG.md
FAQ.md
README.md

Added basic FAQ.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/33)

Added basic FAQ document

---

CHANGELOG.md
include/ad_rss/state/ResponseStateOperation.hpp
src/core/RssCheck.cpp
src/core/RssResponseResolving.cpp
src/core/RssSituationChecking.cpp
src/core/RssState.hpp
tests/CMakeLists.txt
tests/core/RssStateCombineRssStateTests.cpp
tests/state/RssStateSafeTests.cpp

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/42)

Make some ResponseStateOperations public

---

.github/.travis/code_coverage.sh
README.md

Title says all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/47)

Added integration for CodeCov

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/55)

Fixed Travis build issues with gem update

---

doc/BUILDING.md

API documentation update from cmake -BUILD_APIDOC=ON .. to cmake -DBUILD_APIDOC=ON ..
No code change
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/58)

Documentation Fix - API documentation

---

.github/.travis/code_coverage.sh
.github/.travis/deploy.sh
.travis.yml
README.md

- Updated Travis-CI
- Generate API documentation for ad_rss and ad_rss_map_integration
- Generate code coverage info for ad_rss and ad_rss_map_integration
- Update README to match latest release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/62)

Fixed documentation generation and deployment

---

README.md

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/61)

Fix link to BUILD instructions

---

.github/.travis/code_coverage.sh

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/67)

Smart coverage report

---

.github/.travis/deploy.sh

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/68)

fix gh-pages deployment

---

doc/ad_rss/HLD-ArchitectureOverview.md
doc/ad_rss/HLD-KeyDesignDecisionsAndAlternatives.md
doc/ad_rss/SupportedRssFeatures.md
doc/ad_rss_map_integration/Main.md

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/70)

Fix link in docu

---

doc/BUILDING.md
doc/CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/72)

Add step-by-step cmake build example

---

ad_rss/generated/CMakeLists.txt
ad_rss/generated/include/ad_rss/Version.hpp
ad_rss/impl/src/situation/RssUnstructuredSceneChecker.cpp
ad_rss/python/tests/interface_test.py
ad_rss_map_integration/generated/CMakeLists.txt
ad_rss_map_integration/generated/cmake/Config.cmake.in
ad_rss_map_integration/generated/include/ad_rss_map_integration/Version.hpp
ad_rss_map_integration/python/tests/interface_test.py
cmake/python/python_wrapper_helper.py
doc/CHANGELOG.md

Fixed drive away mode in unstructured scenes
Fixed version number of ad_rss_map_integration
Change-Id: Ic68f10815d71f867b8fec1be281299b9698e4f43
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/80)

Bugfix release 4.0.1

---

.travis.yml
ad_rss/generated/CMakeLists.txt
ad_rss/generated/include/ad/rss/world/UnstructuredSettings.hpp
ad_rss/generated/include/ad/rss/world/UnstructuredSettingsValidInputRange.hpp
ad_rss/generated/include/ad_rss/Version.hpp
ad_rss/impl/include/ad/rss/unstructured/DebugDrawing.hpp
ad_rss/impl/include/ad/rss/unstructured/Geometry.hpp
ad_rss/impl/src/situation/RssUnstructuredSceneChecker.cpp
ad_rss/impl/src/unstructured/Geometry.cpp
ad_rss/impl/src/unstructured/TrajectoryCommon.cpp
ad_rss/impl/src/unstructured/TrajectoryCommon.hpp
ad_rss/impl/src/unstructured/TrajectoryPedestrian.cpp
ad_rss/impl/src/unstructured/TrajectoryVehicle.cpp
ad_rss/impl/src/unstructured/TrajectoryVehicle.hpp
ad_rss/impl/test/generated/ad/rss/state/RssStateSnapshotTests.cpp
ad_rss/impl/test/generated/ad/rss/state/RssStateSnapshotValidInputRangeTests.cpp
ad_rss/impl/test/generated/ad/rss/world/RssDynamicsTests.cpp
ad_rss/impl/test/generated/ad/rss/world/RssDynamicsValidInputRangeTests.cpp
ad_rss/impl/test/generated/ad/rss/world/UnstructuredSettingsTests.cpp
ad_rss/impl/test/generated/ad/rss/world/UnstructuredSettingsValidInputRangeTests.cpp
ad_rss/impl/test/generated/ad/rss/world/WorldModelTests.cpp
ad_rss/impl/test/generated/ad/rss/world/WorldModelValidInputRangeTests.cpp
ad_rss/impl/test/unstructured/GeometryTests.cpp
ad_rss_map_integration/generated/CMakeLists.txt
ad_rss_map_integration/generated/cmake/Config.cmake.in
ad_rss_map_integration/generated/include/ad_rss_map_integration/Version.hpp
ad_rss_map_integration/impl/tests/RssSceneCreationTest.hpp
doc/BUILDING.md
doc/CHANGELOG.md
doc/ad_rss/UnstructuredScenes.md

Update unstructured trajectory set calculation + build cleanup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/82)

Unstructured Scenes: Fix trajectory sets

---

cmake/python-binding.cmake
doc/CHANGELOG.md

Make use of the (first) provided target python version for the python code generation process
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/90)

Use target python version for build

---

.github/workflows/build_test.yml
.github/workflows/install_dependencies.sh
README.md

As the title says, added CI for Ubuntu 20.04 with GCC-9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/93)

Added build support/test for Ubuntu 20.04

---

.github/workflows/deploy_documentation.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/94)

Fixed documentation deployment on gh-pages branch

---

.github/workflows/check_documentation.yml
.github/workflows/install_dependencies.sh
ad_rss/impl/src/situation/Physics.cpp
ad_rss/impl/test/situation/PhysicsUnitTestsTimeToCoverDistance.cpp
doc/CHANGELOG.md

The "feature" of maxSpeedOnAcceleration should only limit the actual
acceleration while reponse time.
calculateTimeForDistance(): negative acceleration values have to perform
accelerated movement calculations
calculateTimeToCoverDistance(): maxSpeedOnAcceleration must not be
considered anymore after reponse time
Fixes #95 
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/96)

Fix issue #95

---

colcon.meta
colcon_python.meta

ad_map_opendrive_reader -> PROJ4
ad_map_access_qgis -> ad_map_access
Fixes #99   
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/100)

Fix dependencies

---

.github/workflows/check_documentation.yml

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/105)

Fix documentation build

---

ad_rss_map_integration/python/tests/interface_test.py

and adapted test in respect to map fix
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/109)

Updated map repository

---

.github/workflows/build_test.yml
.github/workflows/wheels.yml
README.md
ad_rss_map_integration/python/generate_python_lib.py.in
colcon.meta
colcon_python.meta
doc/BUILDING.md
doc/CHANGELOG.md
doc/ad_rss/HLD-Security.md

Fixed ad_rss_map_integration python binding build failed in CARLA
environment because of not existing folder beeing referenced
Change-Id: Ida59d2d75f0420106d157fc49f0575130ea0a7e6
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/115)

Fix python binding build

---

doc/CHANGELOG.md

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/118)

update map 2.6.0

---

cmake/ad-rss-lib-version.cmake
doc/CHANGELOG.md

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/119)

Release 4.5.1

---

ad_rss/doc/Doxyfile.in
ad_rss/include/ad/rss/unstructured/DebugDrawing.hpp
ad_rss/include/ad/rss/unstructured/Geometry.hpp
ad_rss_map_integration/doc/Doxyfile.in
ad_rss_map_integration/include/ad/rss/map/Logging.hpp
ad_rss_map_integration/include/ad/rss/map/RssSceneCreation.hpp

Fixes #123  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/124)

Fix doxygen generation

---

cmake/ad-rss-lib-version.cmake
colcon.meta
colcon_python.meta
doc/CHANGELOG.md

and by this also to latest spdlog on v1.x branch
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/127)

Update map to v2.6.2

---

cmake/ad-rss-lib-version.cmake
doc/CHANGELOG.md

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/138)

udpate to version 4.5.3

---

.github/workflows/check_documentation.yml

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/150)

Allow documentation to push

---

.github/dependabot.yml
.github/workflows/check_documentation.yml
.github/workflows/code_coverage.sh
.github/workflows/install_dependencies.sh

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/171)

Try to fix Pinned Dependencies

---

.github/pull_request_template.md
.github/workflows/build_test.yml
.github/workflows/check_documentation.yml
.github/workflows/code_format_check.yml
.github/workflows/codeql.yml
.github/workflows/scorecards.yml
.github/workflows/wheels.yml
README.md
SECURITY.md
doc/FAQ.md
doc/ad_rss/HLD-Security.md
mkdocs.yml

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel/ad-rss-lib/177)

master -> main

---

.github/workflows/codeql.yml
.github/workflows/requirements.txt
.github/workflows/scorecards.yml

Berndgassmann patch 2

---

.github/workflows/check_documentation.yml

ensure docu setup is run with python 3.10

---

.github/workflows/check_documentation.yml
.github/workflows/wheels.yml

Remove Python3.8 from wheels build

---

.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/install_dependencies.sh
.github/workflows/scorecards.yml
ad_rss/CMakeLists.txt
ad_rss/cmake/Config.cmake.in
ad_rss/python/CMakeLists.txt
ad_rss_map_integration/CMakeLists.txt
cmake/python-binding.cmake

Fix warning and errors on CI

---

.github/workflows/wheel.ad-rss-map-integration.yml
.github/workflows/wheel.ad-rss.yml

Fix wheels upload url
